-- MySQL Script generated by MySQL Workbench
-- Tue Sep  4 21:16:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb1` ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb1` DEFAULT CHARACTER SET utf8 ;
USE `mydb1` ;

-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Hotel` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Hotel` (
  `idHotel` INT NOT NULL auto_increment,
  `nazwa` VARCHAR(45) NULL,
  `lokalizacja` VARCHAR(45) NULL,
  `adres_miasto` VARCHAR(45) NULL,
  `adres_kodPocztowy` INT(5) NULL,
  `adres_ulica` VARCHAR(45) NULL,
  `adres_nrBudynku` INT NULL,
  PRIMARY KEY (`idHotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Klient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Klient` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Klient` (
  `idKlient` INT NOT NULL auto_increment,
  `adresMailowy` VARCHAR(45) NULL,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `nrDowodu` VARCHAR(45) NULL,
  `adres_miasto` VARCHAR(45) NULL,
  `adres_kodPocztowy` INT(5) NULL,
  `adres_ulica` VARCHAR(45) NULL,
  `adres_nrBudynku` INT NULL,
  PRIMARY KEY (`idKlient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Masaz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Masaz` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Masaz` (
  `idMasaz` INT NOT NULL auto_increment,
  `cena` INT NULL,
  `czasTtrwania` TIME NULL,
  `godzRozp` DATETIME NULL,
  `godzZak` DATETIME NULL,
  `czyZaliczone` TINYINT NULL,
  `PokojSPA_idPokojSPA` INT NOT NULL,
  `Zamowienie_idZamowienie` INT NOT NULL,
  `Recepcjonista_Pracownik_idPracownik` INT NOT NULL,
  PRIMARY KEY (`idMasaz`, `PokojSPA_idPokojSPA`, `Zamowienie_idZamowienie`, `Recepcjonista_Pracownik_idPracownik`),
  INDEX `fk_Masaz_PokojSPA1_idx` (`PokojSPA_idPokojSPA` ASC),
  INDEX `fk_Masaz_Zamówienie1_idx` (`Zamowienie_idZamowienie` ASC),
  INDEX `fk_Masaz_Recepcjonista1_idx` (`Recepcjonista_Pracownik_idPracownik` ASC),
  CONSTRAINT `fk_Masaz_PokojSPA1`
    FOREIGN KEY (`PokojSPA_idPokojSPA`)
    REFERENCES `mydb1`.`PokojSPA` (`idPokojSPA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Masaz_Zamowienie1`
    FOREIGN KEY (`Zamowienie_idZamowienie`)
    REFERENCES `mydb1`.`Zamowienie` (`idZamowienie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Masaz_Recepcjonista1`
    FOREIGN KEY (`Recepcjonista_Pracownik_idPracownik`)
    REFERENCES `mydb1`.`Recepcjonista` (`Pracownik_idPracownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menedzer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Menedzer` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Menedzer` (
  `Pracownik_idPracownik` INT NOT NULL,
  PRIMARY KEY (`Pracownik_idPracownik`),
  INDEX `fk_Menedzer_Pracownik1_idx` (`Pracownik_idPracownik` ASC),
  CONSTRAINT `fk_Menedzer_Pracownik1`
    FOREIGN KEY (`Pracownik_idPracownik`)
    REFERENCES `mydb1`.`Pracownik` (`idPracownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Naleznosc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Naleznosc` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Naleznosc` (
  `idNaleznosc` INT NOT NULL auto_increment,
  `stanRealizacji` VARCHAR(45) NULL,
  `data` DATETIME NULL,
  `Pobyt_idPobyt` INT NOT NULL,
  PRIMARY KEY (`idNaleznosc`, `Pobyt_idPobyt`),
  INDEX `fk_Naleznosc_Pobyt1_idx` (`Pobyt_idPobyt` ASC),
  CONSTRAINT `fk_Naleznosc_Pobyt1`
    FOREIGN KEY (`Pobyt_idPobyt`)
    REFERENCES `mydb1`.`Pobyt` (`idPobyt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pietro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Pietro` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Pietro` (
  `idPietro` INT NOT NULL auto_increment,
  `Hotel_idHotel` INT NOT NULL,
  `ktorePietro` INT NOT NULL,
  PRIMARY KEY (`idPietro`, `Hotel_idHotel`),
  INDEX `fk_Pietro_Hotel1_idx` (`Hotel_idHotel` ASC),
  UNIQUE INDEX `idPietro_UNIQUE` (`idPietro` ASC),
  CONSTRAINT `fk_Pietro_Hotel1`
    FOREIGN KEY (`Hotel_idHotel`)
    REFERENCES `mydb1`.`Hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pobyt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Pobyt` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Pobyt` (
  `idPobyt` INT NOT NULL auto_increment,
  `dataRozpoczecia` DATETIME NULL,
  `dataZakonczenia` DATETIME NULL,
  `Zamowienie_idZamowienie` INT NOT NULL,
  PRIMARY KEY (`idPobyt`, `Zamowienie_idZamowienie`),
  INDEX `fk_Pobyt_Zamowienie1_idx` (`Zamowienie_idZamowienie` ASC),
  CONSTRAINT `fk_Pobyt_Zamowienie1`
    FOREIGN KEY (`Zamowienie_idZamowienie`)
    REFERENCES `mydb1`.`Zamowienie` (`idZamowienie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pokoj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Pokoj` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Pokoj` (
  `nrPokoju` INT NOT NULL auto_increment,
  `StandardPokoju_idStandardPokoju` INT NOT NULL,
  `Pietro_idPietro` INT NOT NULL,
  `WidokZOkna_idWidokZOkna` INT NOT NULL,
  `Rezerwacja_idRezerwacja` INT NULL,
  `Cena` INT NOT NULL,
  `Rabat_kod` VARCHAR(8) NULL,
  PRIMARY KEY (`nrPokoju`, `StandardPokoju_idStandardPokoju`, `Pietro_idPietro`, `WidokZOkna_idWidokZOkna`),
  INDEX `fk_Pokoj_StandardPokoju1_idx` (`StandardPokoju_idStandardPokoju` ASC),
  INDEX `fk_Pokoj_Pietro1_idx` (`Pietro_idPietro` ASC),
  INDEX `fk_Pokoj_WidokZOkna1_idx` (`WidokZOkna_idWidokZOkna` ASC),
  INDEX `fk_Pokoj_Rezerwacja1_idx` (`Rezerwacja_idRezerwacja` ASC),
  INDEX `fk_Pokoj_Rabat1_idx` (`Rabat_kod` ASC),
  CONSTRAINT `fk_Pokoj_StandardPokoju1`
    FOREIGN KEY (`StandardPokoju_idStandardPokoju`)
    REFERENCES `mydb1`.`StandardPokoju` (`idStandardPokoju`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokoj_Pietro1`
    FOREIGN KEY (`Pietro_idPietro`)
    REFERENCES `mydb1`.`Pietro` (`idPietro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokoj_WidokZOkna1`
    FOREIGN KEY (`WidokZOkna_idWidokZOkna`)
    REFERENCES `mydb1`.`WidokZOkna` (`idWidokZOkna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokoj_Rezerwacja1`
    FOREIGN KEY (`Rezerwacja_idRezerwacja`)
    REFERENCES `mydb1`.`Rezerwacja` (`idRezerwacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokoj_Rabat1`
    FOREIGN KEY (`Rabat_kod`)
    REFERENCES `mydb1`.`Rabat` (`kod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PokojSPA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`PokojSPA` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`PokojSPA` (
  `idPokojSPA` INT NOT NULL auto_increment,
  `rodzajUslugi` VARCHAR(45) NULL,
  `rodzajPomieszczenia` VARCHAR(45) NULL,
  `Hotel_idHotel` INT NOT NULL,
  PRIMARY KEY (`idPokojSPA`, `Hotel_idHotel`),
  INDEX `fk_PokojSPA_Hotel1_idx` (`Hotel_idHotel` ASC),
  CONSTRAINT `fk_PokojSPA_Hotel1`
    FOREIGN KEY (`Hotel_idHotel`)
    REFERENCES `mydb1`.`Hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pracownik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Pracownik` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Pracownik` (
  `idPracownik` INT NOT NULL auto_increment,
  `nazwisko` VARCHAR(45) NULL,
  `imie` VARCHAR(45) NULL,
  `PESEL` INT(11) NULL,
  `pensja` DOUBLE NULL,
  `adres_miasto` VARCHAR(45) NULL,
  `adres_kodPocztowy` INT(5) NULL,
  `adres_ulica` VARCHAR(45) NULL,
  `adres_nrBudynku` INT NULL,
  `Hotel_idHotel` INT NOT NULL,
  PRIMARY KEY (`idPracownik`, `Hotel_idHotel`),
  INDEX `fk_Pracownik_Hotel1_idx` (`Hotel_idHotel` ASC),
  CONSTRAINT `fk_Pracownik_Hotel1`
    FOREIGN KEY (`Hotel_idHotel`)
    REFERENCES `mydb1`.`Hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rabat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Rabat` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Rabat` (
  `kod` VARCHAR(8) NOT NULL,
  `% Obnizki` INT NULL,
  `usluga` VARCHAR(45) NULL,
  `data_rozpoczecia` DATETIME NULL,
  `data_zakonczenia` DATETIME NULL,
  `Menedzer_Pracownik_idPracownik` INT NOT NULL,
  PRIMARY KEY (`kod`, `Menedzer_Pracownik_idPracownik`),
  INDEX `fk_Rabat_Menedzer1_idx` (`Menedzer_Pracownik_idPracownik` ASC),
  CONSTRAINT `fk_Rabat_Menedzer1`
    FOREIGN KEY (`Menedzer_Pracownik_idPracownik`)
    REFERENCES `mydb1`.`Menedzer` (`Pracownik_idPracownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recepcjonista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Recepcjonista` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Recepcjonista` (
  `Pracownik_idPracownik` INT NOT NULL ,
  PRIMARY KEY (`Pracownik_idPracownik`),
  CONSTRAINT `fk_Recepcjonista_Pracownik1`
    FOREIGN KEY (`Pracownik_idPracownik`)
    REFERENCES `mydb1`.`Pracownik` (`idPracownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reszta kwoty`
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Table `mydb`.`Rezerwacja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Rezerwacja` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Rezerwacja` (
  `idRezerwacja` INT NOT NULL auto_increment,
  PRIMARY KEY (`idRezerwacja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sezon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Sezon` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Sezon` (
  `idSezon` INT NOT NULL auto_increment,
  `miesiac_od` CHAR(11) NULL,
  `miesiac_do` CHAR(11) NULL,
  PRIMARY KEY (`idSezon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StandardPokoju`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`StandardPokoju` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`StandardPokoju` (
  `idStandardPokoju` INT NOT NULL auto_increment,
  `udogodnienia` VARCHAR(45) NULL,
  `liczbaPomieszczen` INT NULL,
  `StandardPokoju` VARCHAR(45) NULL,
  `maxLiczbaOsob` INT NULL,
  PRIMARY KEY (`idStandardPokoju`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WidokZOkna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`WidokZOkna` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`WidokZOkna` (
  `idWidokZOkna` INT NOT NULL auto_increment,
  `Widok` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idWidokZOkna`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zaliczka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Zaliczka` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Zaliczka` (
  `idZaliczka` INT NOT NULL auto_increment,
  PRIMARY KEY (`idZaliczka`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zamowienie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb1`.`Zamowienie` ;

CREATE TABLE IF NOT EXISTS `mydb1`.`Zamowienie` (
  `idZamowienie` INT NOT NULL auto_increment,
  `data_od` DATETIME NULL,
  `data_do` DATETIME NULL,
  `cena` DOUBLE NULL,
  `Klient_idKlient` INT NOT NULL,
  `Rezerwacja_idRezerwacja` INT NOT NULL,
  `Pokoj_nrPokoju` INT NOT NULL,
  PRIMARY KEY (`idZamowienie`, `Klient_idKlient`, `Rezerwacja_idRezerwacja`, `Pokoj_nrPokoju`),
  INDEX `fk_Zamówienie_Klient1_idx` (`Klient_idKlient` ASC),
  INDEX `fk_Zamówienie_Rezerwacja1_idx` (`Rezerwacja_idRezerwacja` ASC),
  INDEX `fk_Zamówienie_Pokój1_idx` (`Pokoj_nrPokoju` ASC),
  CONSTRAINT `fk_Zamówienie_Klient1`
    FOREIGN KEY (`Klient_idKlient`)
    REFERENCES `mydb1`.`Klient` (`idKlient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zamówienie_Rezerwacja1`
    FOREIGN KEY (`Rezerwacja_idRezerwacja`)
    REFERENCES `mydb1`.`Rezerwacja` (`idRezerwacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zamówienie_Pokój1`
    FOREIGN KEY (`Pokoj_nrPokoju`)
    REFERENCES `mydb1`.`Pokoj` (`nrPokoju`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
